name: cryptocalc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.0.0
  hive_ce: ^2.11.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  url_launcher: ^6.3.1
  collection: ^1.19.1
  provider: ^6.1.5
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  flutter_native_timezone_latest: ^1.0.0
  either_dart: ^1.0.0
  workmanager: ^0.7.0
  async: ^2.13.0
  intl: ^0.20.2
  http: ^1.4.0
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  build_runner: ^2.5.2
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  hive_ce_generator: ^1.9.2
  icons_launcher: ^3.0.1

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
